workspace:
  base: /srv/app
  path: src/dev.sigpipe.me/dashie/git.txt

clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: true

pipeline:
  test:
    image: webhippie/golang:edge
    pull: true
    environment:
      TAGS: sqlite
      GOPATH: /srv/app
    commands:
      - echo 'http://dl-cdn.alpinelinux.org/alpine/v3.7/main' >> /etc/apk/repositories
      - apk update
      - apk -U add libmagic file-dev libgit2=0.25.1-r4 libgit2-dev=0.25.1-r4
      - make test
    when:
      event: [ push, tag, pull_request ]

  build:
    image: webhippie/golang:edge
    pull: true
    environment:
      TAGS: sqlite
      GOPATH: /srv/app
    commands:
      - echo 'http://dl-cdn.alpinelinux.org/alpine/v3.7/main' >> /etc/apk/repositories
      - apk update
      - apk -U add libmagic file-dev libgit2=0.25.1-r4 libgit2-dev=0.25.1-r4
      - make clean
      - make vet
      - make lint
      - make misspell-check
      - make build
    when:
      event: [ push, tag, pull_request ]

  static_Linux_x86_64:
    image: webhippie/golang:edge
    pull: true
    environment:
      TAGS: sqlite
      GOPATH: /srv/app
    commands:
      - echo 'http://dl-cdn.alpinelinux.org/alpine/v3.7/main' >> /etc/apk/repositories
      - apk update
      - apk -U add libmagic file-dev libgit2=0.25.1-r4 libgit2-dev=0.25.1-r4
      - make clean
      - make build
      - make release-lx64
    when:
      event: [ push, tag ]

#  release:
#    image: plugins/s3:1
#    pull: true
#    secrets: [ aws_access_key_id, aws_secret_access_key ]
#    bucket: drone-git.txt
#    endpoint: https://s3.sigpipe.me
#    path_style: true
#    strip_prefix: dist/release/
#    source: dist/release/*.tgz
#    target: /git.txt/${DRONE_TAG##v}
#    when:
#      event: [ tag ]

#  release:
#      image: plugins/s3:1
#      pull: true
#      secrets: [ aws_access_key_id, aws_secret_access_key ]
#      bucket: drone-git.txt
#      endpoint: https://s3.sigpipe.me
#      path_style: true
#      strip_prefix: dist/release/
#      source: dist/release/*.tgz
#      target: /git.txt/master
#      when:
#        event: [ push ]
#        branch: [ master ]

#  static:
#    image: karalabe/xgo-latest:latest
#    pull: true
#    environment:
#      TAGS: sqlite
#      GOPATH: /srv/app
#    commands:
#      - make clean
#      - make release
#    when:
#      event: [ push, tag ]
#
#  release:
#    image: plugins/s3:1
#    pull: true
#    secrets: [ s3_ak, s3_sk ]
#    bucket: drone-git.txt
#    endpoint: https://s3.sigpipe.me
#    path_style: true
#    strip_prefix: dist/release/
#    source: dist/release/*
#    target: /git.txt/${DRONE_TAG##v}
#    when:
#      event: [ tag ]
#
#  release:
#    image: plugins/s3:1
#    pull: true
#    secrets: [ s3_ak, s3_sk ]
#    bucket: releases
#    endpoint: https://s3.sigpipe.me
#    path_style: true
#    strip_prefix: dist/release/
#    source: dist/release/*
#    target: /git.txt/master
#    when:
#      event: [ push ]
#      branch: [ master ]

  notify:
    image: plugins/slack
    channel: gitea
    secrets:
      - SLACK_WEBHOOK
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure, success ]
