workspace:
  base: /srv/app
  path: src/dev.sigpipe.me/dashie/git.txt

pipeline:
  clone:
    image: plugins/git
    depth: 50
    tags: true

  test:
    image: webhippie/golang:edge
    pull: true
    environment:
      TAGS: sqlite
      GOPATH: /srv/app
    commands:
      - apk -U add libmagic file-dev libgit2 libgit2-dev
      - make test
    when:
      event: [ push, tag, pull_request ]

  build:
    image: webhippie/golang:edge
    pull: true
    environment:
      TAGS: sqlite
      GOPATH: /srv/app
    commands:
      - apk -U add libmagic file-dev libgit2 libgit2-dev
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - make clean
      - make vet
      - make lint
      - make misspell-check
      - make build
    when:
      event: [ push, tag, pull_request ]

  static:
    image: karalabe/xgo-latest:latest
    pull: true
    environment:
      TAGS: sqlite
      GOPATH: /srv/app
    commands:
      - make release
    when:
      event: [ push, tag ]

  release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_ak, s3_sk ]
    bucket: drone-git.txt
    endpoint: https://s3.sigpipe.me
    path_style: true
    strip_prefix: dist/release/
    source: dist/release/*
    target: /git.txt/${DRONE_TAG##v}
    when:
      event: [ tag ]

  release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_ak, s3_sk ]
    bucket: releases
    endpoint: https://s3.sigpipe.me
    path_style: true
    strip_prefix: dist/release/
    source: dist/release/*
    target: /git.txt/master
    when:
      event: [ push ]
      branch: [ master ]

  notify:
    image: plugins/slack
    channel: gitea
    secrets:
      - SLACK_WEBHOOK
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure, success ]
