
## Gopkg.toml example (these lines may be deleted)

## "metadata" defines metadata about the project that could be used by other independent
## systems. The metadata defined here will be ignored by dep.
# [metadata]
# key1 = "value that convey data to other systems"
# system1-data = "value that is used by a system"
# system2-data = "value that is used by another system"

## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
# required = ["github.com/user/thing/cmd/thing"]

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
# ignored = ["github.com/user/project/badpkg"]

## Constraints are rules for how directly imported projects
## may be incorporated into the depgraph. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
# [[constraint]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"
#
## "metadata" defines metadata about the dependency or override that could be used
## by other independent systems. The metadata defined here will be ignored by dep.
# [metadata]
# key1 = "value that convey data to other systems"
# system1-data = "value that is used by a system"
# system2-data = "value that is used by another system"

## Overrides have the same structure as [[constraint]], but supersede all
## [[constraint]] declarations from all projects. Only [[override]] from
## the current project's are applied.
##
## Overrides are a sledgehammer. Use them only as a last resort.
# [[override]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Optional: specifying a version constraint override will cause all other
## constraints on this project to be ignored; only the overridden constraint
## need be satisfied.
## Again, only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: specifying an alternate source location as an override will
## enforce that the alternate location is used for that project, regardless of
## what source location any dependent projects specify.
# source = "https://github.com/myfork/package.git"



[[constraint]]
  name = "github.com/Unknwon/com"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/Unknwon/paginater"

[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/binding"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/cache"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/csrf"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/i18n"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/session"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/toolbox"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-xorm/core"
  version = "0.5.6"

[[constraint]]
  name = "github.com/go-xorm/xorm"
  version = "0.6.2"

[[constraint]]
  name = "github.com/gogits/cron"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/jaytaylor/html2text"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  branch = "master"
  name = "github.com/rakyll/magicmime"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.4.0"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.2"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/clog.v1"
  version = "1.1.1"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  version = "2.0.0"

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "1.27.2"

[[constraint]]
  branch = "v25"
  name = "gopkg.in/libgit2/git2go.v25"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.2.1"
